substitutions:
  friendly_name: Zehnder ComfoAir Q350
  device_name: zehnder-comfoair-q350
  device_description: Ventilation system
  filter_time: 5s
  filter_send_every: '1'
  filter_window_size: '3'

packages:
  canbus: !include packages/canbus.yml
  binary_sensors: !include packages/binary_sensors.yml
  button: !include packages/button.yml
  select: !include packages/select.yml
  sensors: !include packages/sensors.yml
  switch: !include packages/switch.yml
  text_sensors: !include packages/text_sensors.yml
  fan: !include packages/fan.yml
  climate: !include packages/climate.yml

  device_base: !include boards/m5stack-atoms3.yml

external_components:
  - source: github://yoziru/esphome-zehnder-comfoair
    components: [ zehnder_comfoair_q ]

esphome:
  name: ${device_name}
  # name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}

logger:
  level: INFO
  logs:
    canbus: INFO

api:
  encryption:
    key: !secret api_encryption_key

# sync time with home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "{device_name}-ap"
    password: !secret wifi_hotspot_password

captive_portal:

# See docs: https://github.com/michaelarnauts/aiocomfoconnect/blob/master/docs/PROTOCOL-PDO.md
zehnder_comfoair_q:
  id: comfoair
  request_ids: [16, 49, 54, 55, 65, 66, 67, 81, 82, 117, 118, 119, 120, 121, 122, 128, 129, 130, 192, 209, 210, 211, 212, 212, 213, 214, 215, 216, 217, 218, 220, 221, 225, 227, 274, 275, 276, 277, 278, 290, 291, 292, 293, 294]
